CREATE TABLE BacASableRapportProdAsten(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_fichier] [numeric](15, 5) NULL,
	[Flag_Fichier] [numeric](8, 0) NULL,
	[ID_jour] [numeric](15, 5) NULL,
	[Domaine] [varchar](100) NULL,
	[Serveur] [varchar](100) NULL,
	[Tache] [varchar](100) NULL,
	[MU] [varchar](100) NULL,
	[Unite_de_gestion] [varchar](100) NULL,
	[sess] [varchar](100) NULL,
	[Session] [varchar](100) NULL,
	[Job] [varchar](100) NULL,
	[Uproc] [varchar](100) NULL,
	[Statut] [varchar](100) NULL,
	[Prevu] [datetime] NULL,
	[Debut] [datetime] NULL,
	[Fin] [datetime] NULL,
	[Duree] [datetime] NULL,
	[Temps_estime] [datetime] NULL,
	[Fil_rouge] [numeric](15, 5) NULL,
	[Info] [varchar](100) NULL,
	[Date_creation_fichier] [datetime] NULL,
	[Date_derniere_modification] [datetime] NULL,
	[Nom_du_fichier] [varchar](100) NULL,
	[Nombre_de_lignes] [numeric](15, 5) NULL,
	[Taille_du_fichier] [numeric](15, 5) NULL,
	[Auteur_du_fichier] [varchar](100) NULL
)